import random
from dataclasses import dataclass

from content.style_guide import (
    BRAND_LINE,
    DEFAULT_MIN_WORDS,
    FACT_RULES,
    FORMAT_RULES,
    MIN_WORDS_DEFAULT,
    MIN_WORDS_MEDIUM,
    MIN_WORDS_PREMIUM,
    MIN_WORDS_SHORT,
    build_voice_block,
)


@dataclass
class ContentType:
    key: str
    label: str
    weight: int  # relative weight for rotation
    emoji: str
    hashtags: str = ""
    min_words: int = DEFAULT_MIN_WORDS


CONTENT_TYPES = {
    "micro_protocol": ContentType(
        key="micro_protocol",
        label="Микро-протокол",
        weight=5,
        emoji="\u2699\ufe0f",
        hashtags="#нейронаука #мозг #продуктивность #фокус #привычки",
    ),
    "myth_buster": ContentType(
        key="myth_buster",
        label="Разбор мифа",
        weight=4,
        emoji="\u274c",
        hashtags="#нейронаука #мозг #мифы #наука #здоровье",
    ),
    "research_digest": ContentType(
        key="research_digest",
        label="Разбор исследования",
        weight=4,
        emoji="\U0001f52c",
        hashtags="#нейронаука #исследования #мозг #наука #память",
    ),
    "morning_routine": ContentType(
        key="morning_routine",
        label="Утренний протокол",
        weight=3,
        emoji="\u2600\ufe0f",
        hashtags="#нейронаука #утро #энергия #привычки #сон",
    ),
    "evening_reflection": ContentType(
        key="evening_reflection",
        label="Вечерний совет",
        weight=2,
        emoji="\U0001f319",
        hashtags="#сон #восстановление #нейронаука #вечер #стресс",
    ),
    "poll": ContentType(
        key="poll",
        label="Опрос",
        weight=3,
        emoji="\U0001f4ca",
        hashtags="#мозг #продуктивность #опрос #привычки",
        min_words=MIN_WORDS_SHORT,
    ),
    # Оффтоп-рубрики: жизнь канала шире, чем «полезные советы».
    "supplement_recap": ContentType(
        key="supplement_recap",
        label="Разбор БАДов",
        weight=3,
        emoji="\U0001f9ea",
        hashtags="#бады #исследования #здоровье #добавки #наука",
    ),
    "health_news": ContentType(
        key="health_news",
        label="Новость здоровья",
        weight=3,
        emoji="\U0001f4f0",
        hashtags="#новостинауки #здоровье #мозг #исследования",
        min_words=MIN_WORDS_MEDIUM,
    ),
    "brain_curiosity": ContentType(
        key="brain_curiosity",
        label="Нейро-загадка",
        weight=3,
        emoji="\U0001f9e9",
        hashtags="#нейронаука #мозг #загадкимозга #наука #сознание",
    ),
}

# Short emoji rubric. Kept deliberately minimal: a long uppercase label at
# the top of every post is one of the strongest "generated by a bot" tells.
RUBRIC_TAGS = {
    "micro_protocol": "\u2699\ufe0f протокол",
    "myth_buster": "\u274c разбор мифа",
    "research_digest": "\U0001f52c исследование",
    "morning_routine": "\u2600\ufe0f утро",
    "evening_reflection": "\U0001f319 вечер",
    "poll": "\U0001f4ca опрос",
    "supplement_recap": "\U0001f9ea разбор добавок",
    "health_news": "\U0001f4f0 новости здоровья",
    "brain_curiosity": "\U0001f9e9 загадка мозга",
}

# Premium content types
PREMIUM_CONTENT_TYPES = {
    "deep_dive": ContentType(
        key="deep_dive",
        label="Глубокий разбор",
        weight=5,
        emoji="\U0001f9ec",
    ),
    "protocol_plus": ContentType(
        key="protocol_plus",
        label="Протокол+",
        weight=4,
        emoji="\U0001f48e",
    ),
    "weekly_digest": ContentType(
        key="weekly_digest",
        label="Недельный дайджест",
        weight=3,
        emoji="\U0001f4f0",
    ),
}

PREMIUM_RUBRIC_TAGS = {
    "deep_dive": "\U0001f9ec глубокий разбор",
    "protocol_plus": "\U0001f48e протокол+",
    "weekly_digest": "\U0001f4f0 дайджест недели",
}

SYSTEM_PROMPT = f"""{BRAND_LINE}

{FORMAT_RULES}
{FACT_RULES}
{build_voice_block()}
Тема поста указана в начале сообщения — пиши строго про неё и не подменяй её своей."""

PREMIUM_SYSTEM_PROMPT = f"""Ты пишешь для закрытого канала SpectrMind Premium — для тех, кто читает канал давно и хочет копнуть глубже.

{FACT_RULES}
{FORMAT_RULES}
{build_voice_block()}
Дополнительно для премиума:
— Разбирай механизм: что именно происходит в мозге или теле и почему это даёт наблюдаемый эффект.
— Показывай, где данные противоречат друг другу, и что это значит на практике.
— Объём 400–700 слов, но без воды: каждое предложение несёт новую информацию.
— Практическая часть — конкретные действия, а не общие пожелания.

Тема поста указана в начале сообщения — пиши строго про неё и не подменяй её своей."""

PROMPTS = {
    "micro_protocol": """Пост-протокол: одна конкретная практика и почему она работает.

Структура (свободная, не по пунктам):
1. Зацепка — ситуация, в которой читатель узнает себя.
2. Суть практики — что делать, своими словами, без пошагового шаблона «Шаг 1, Шаг 2» и без нумерации.
3. Почему это работает — механизм и данные исследований.
4. Кому не подойдёт или где эффект переоценён.
5. Приглашение: предложи попробовать и рассказать о результате в комментариях.

Объём: 180–320 слов. Не превращай в инструкцию — это текст для чтения.""",

    "myth_buster": """Пост-разбор мифа: популярное утверждение против данных.

Структура (свободная):
1. Зацепка — сам миф, как его обычно формулируют.
2. Почему в него верят: откуда он взялся и в чём доля правды.
3. Что показывают исследования — с конкретикой, где она есть.
4. Где границы: что мы всё ещё не знаем.
5. Практический вывод — одно предложение, что с этим делать.

Объём: 180–320 слов. Не высмеивай читателя за то, что он верил: объясняй, откуда миф взялся.""",

    "research_digest": """Пост-разбор исследования: одна работа и что она реально меняет.

Структура (свободная):
1. Зацепка — результат исследования как интрига.
2. Кого и как изучали: сколько человек, как долго, что измеряли.
3. Главные результаты — 2–3 вывода с цифрами.
4. Что это значит в реальной жизни, без преувеличений.
5. Ограничения: насколько можно доверять и что не проверяли.

Объём: 180–350 слов. Ссылку на источник дай по-человечески, прямо в тексте — «в работе 2021 года», «в обзоре в Sleep Medicine». Не изображай точную библиографию, если не уверен в деталях.""",

    "morning_routine": """Утренний пост: как начать день так, чтобы мозг был на стороне читателя.

Структура (свободная):
1. Зацепка — знакомое утреннее состояние (туман, телефон в руке, спешка).
2. Что происходит в мозге и теле в первые час-полтора после пробуждения.
3. 3–4 конкретных действия, каждое с одной фразой обоснования — прозой, не списком ради списка.
4. Приглашение попробовать и отметить, что изменилось.

Объём: 180–320 слов. Пиши как человек, который сам так делает, а не как автор методички.""",

    "evening_reflection": """Вечерний пост: восстановление и подготовка ко сну.

Структура (свободная):
1. Зацепка — вечерняя проблема: не могу уснуть, мысли по кругу, телефон до последнего.
2. Что мешает организму переключиться: механизм, коротко.
3. 2–3 действия с обоснованием.
4. Спокойное завершение — без пафоса и без «берегите себя».

Объём: 180–320 слов. Тон тише, чем в утренних постах, но не медитативный.""",

    "poll": """Пост-опрос для канала.

Структура:
1. Короткий контекст — 2–3 живых предложения: почему этот вопрос интересен и что об этом известно.
2. Вопрос.
3. Четыре варианта ответа, каждый с новой строки, без нумерации и без эмодзи-маркеров, максимум 5 слов каждый.
4. Одна строка-приглашение проголосовать и написать свой вариант в комментариях.

Объём: 80–160 слов. Контекст должен быть содержательным, а не «давайте узнаем ваше мнение».""",

    "supplement_recap": """Пост-разбор добавки: что реально показали исследования.

Важно: ты НЕ рекомендуешь добавки и НЕ называешь дозы и схемы приёма. Ты разбираешь доказательную базу — как научный обозреватель.

Структура (свободная):
1. Зацепка — обещание, которое дают про эту добавку в рекламе или в соцсетях.
2. Что она вообще делает по механизму — коротко и без спекуляций.
3. Что показали исследования: где эффект подтверждён, где слабый, где нулевой. С цифрами, если помнишь их точно.
4. Честный вывод: стоит ли верить обещаниям и что важнее добавки.
5. Приглашение — спросить читателей об их опыте.

Объём: 180–350 слов.
Категорически нельзя: дозы, схемы приёма, «пропейте курс», «принимайте по утрам», советы сочетать добавки. Если хочется назвать дозу — вместо этого скажи, что дозировки в исследованиях различались.""",

    "health_news": """Пост-новость из мира здоровья и нейронауки.

Структура (свободная):
1. Зацепка — сам новостной факт или результат, одной сильной фразой.
2. Что именно выяснили и кто: исследование, обзор, отчёт ВОЗ или крупной клиники.
3. Почему это важно — что меняется в понимании или в практике.
4. Что это значит для читателя: реалистично, без «спасения человечества».
5. Что пока неясно и чего ждать дальше.

Объём: 150–280 слов. Новость должна быть настоящей: если не уверен, что такое исследование существует, возьми общеизвестный факт и подай его как «данные последних лет», а не выдумывай свежую дату.""",

    "brain_curiosity": """Пост-загадка о мозге: эффект «а я этого не знал».

Структура (свободная):
1. Зацепка — странный факт или вопрос, на который читатель не знает ответа.
2. Разворот: почему интуиция обманывает.
3. Что говорит наука — механизм и данные, с реальным исследованием или автором, где это уместно.
4. Итог: как это меняет взгляд на собственный мозг.
5. Одна догадка-вопрос читателю, на который нет однозначного ответа.

Объём: 180–350 слов. Никакой мистики и эзотерики: если явление объясняют плохо, так и скажи — «границы объяснения здесь честно заканчиваются». Не подавай непроверенное как установленное.""",
}

PREMIUM_PROMPTS = {
    "deep_dive": """Премиум-разбор одного исследования — глубоко, но человеческим языком.

Структура (свободная):
1. Зацепка — вопрос, на который отвечает работа.
2. Как её проводили: сколько участников, как долго, что измеряли, какие методы.
3. Ключевые результаты — 3–5 выводов с конкретными цифрами.
4. Механизм: что происходит на уровне нейробиологии и почему результат такой.
5. Практическое применение — 3–4 действия.
6. Ограничения: что признают сами авторы и где выводы не переносятся на всех.
7. Источник — по-человечески, без имитации библиографии.

Объём: 400–700 слов. Хук в первой строке обязателен: это текст, а не абстракт.""",

    "protocol_plus": """Премиум-протокол: детальная программа с обоснованием.

Структура (свободная):
1. Зацепка — проблема, с которой читатель живёт.
2. Научная база: 2–3 исследования, на которых всё держится, с сутью каждого.
3. Сам протокол: 5–7 шагов с пояснением, зачем нужен каждый. Прозой, а не формальным списком «Шаг 1».
4. Тайминг: когда, сколько по времени, в каком порядке.
5. Что ожидать и когда: реалистично, в неделях, а не в днях.
6. Когда лучше не делать: ограничения и признаки, что не подходит.
7. Две-три детали, которые повышают шанс, что протокол доживёт до привычки.

Объём: 400–700 слов. Не назначай препараты и дозировки — это не медицинская инструкция.""",

    "weekly_digest": """Премиум-дайджест: главное в нейронауке за неделю, без пересказа пресс-релизов.

Структура (свободная):
1. Зацепка — общая линия недели: что связывает эти работы.
2. Три открытия, каждое — отдельными абзацами: суть, что нашли, почему это важно, насколько можно доверять.
3. Что из этого противоречит прежним представлениям.
4. Один вывод для читателя и одно конкретное действие.

Объём: 400–700 слов. Не выдумывай свежие даты и названия: если не уверен в конкретной работе, говори о направлении исследований и о том, что в нём известно достоверно.""",
}


def get_random_content_type() -> str:
    """Pick a content type using weighted random selection."""
    types = list(CONTENT_TYPES.values())
    weights = [t.weight for t in types]
    chosen = random.choices(types, weights=weights, k=1)[0]
    return chosen.key


def get_prompt(content_type: str) -> str:
    """Get the generation prompt for a content type."""
    return PROMPTS.get(content_type, PROMPTS["micro_protocol"])


def get_emoji(content_type: str) -> str:
    """Get the emoji prefix for a content type."""
    ct = CONTENT_TYPES.get(content_type)
    return ct.emoji if ct else "\U0001f9e0"


def get_hashtags(content_type: str) -> str:
    """Get the hashtag line for a content type."""
    ct = CONTENT_TYPES.get(content_type)
    return ct.hashtags if ct else ""


def get_min_words(content_type: str) -> int:
    """Get the minimum acceptable word count for a content type."""
    ct = CONTENT_TYPES.get(content_type)
    return ct.min_words if ct else DEFAULT_MIN_WORDS


def get_premium_min_words() -> int:
    """Premium posts are long-form by definition."""
    return MIN_WORDS_PREMIUM


def get_rubric_tag(content_type: str) -> str:
    """Get the rubric tag for a content type."""
    return RUBRIC_TAGS.get(content_type, "")


# Morning slot types (protocol-first strategy: practice > facts)
MORNING_TYPES = ["micro_protocol", "morning_routine"]
# Midday and evening types: full rotation, including the off-topic rubrics
DAY_EVENING_TYPES = [
    "micro_protocol", "myth_buster", "research_digest", "evening_reflection", "poll",
    "supplement_recap", "health_news", "brain_curiosity",
]

# Rubrics that get extra weight in the 09:00 slot.
MORNING_BOOSTED = ("micro_protocol", "morning_routine")


def get_content_type_for_slot(hour: int) -> str:
    """Pick a content type based on the time slot.

    There is a single daily post at 09:00, so the slot cannot be too
    restrictive: the morning rubrics get double weight, while the rest of
    the rotation (including off-topic rubrics) stays possible. That keeps
    a daily rhythm — protocols most often, with supplements, health news
    and brain trivia mixed in.
    """
    types = list(CONTENT_TYPES.values())
    weights = []
    for t in types:
        weight = t.weight
        if hour < 10 and t.key in MORNING_BOOSTED:
            weight *= 2
        weights.append(weight)
    chosen = random.choices(types, weights=weights, k=1)[0]
    return chosen.key


def get_premium_content_type() -> str:
    """Pick a random premium content type using weighted selection."""
    types = list(PREMIUM_CONTENT_TYPES.values())
    weights = [t.weight for t in types]
    chosen = random.choices(types, weights=weights, k=1)[0]
    return chosen.key


def get_premium_prompt(content_type: str) -> str:
    """Get the generation prompt for a premium content type."""
    return PREMIUM_PROMPTS.get(content_type, PREMIUM_PROMPTS["deep_dive"])


def get_premium_rubric_tag(content_type: str) -> str:
    """Get the rubric tag for a premium content type."""
    return PREMIUM_RUBRIC_TAGS.get(content_type, "")
